server:
  port: 8090

spring:
  application:
    name: consumer-service # ·şÎñÃû³Æ
  sleuth:
    trace-id128: true
    sampler:
      probability: 0.1
    zipkin:
      base-url: http://127.0.0.1:9411